version: "3.9"

services:
  master:
    container_name: master
    image: redis:7
    command: bash -c "redis-server --appendonly yes --requirepass password"
    ports:
      - "6379:6379"
    networks:
      - redis-replication
    volumes:
      - ./data:/data

  replica:
    container_name: replica
    image: redis:7
    command: redis-server /etc/redis.conf --replicaof master 6379
    ports:
      - "6380:6379"
    depends_on:
      - master
    volumes:
      - ./redis.conf:/etc/redis.conf
    networks:
      - redis-replication

networks:
  redis-replication:
    driver: bridge