version: '3.9'

services:
  redis-primary:
    image: redis:latest
    command: ["redis-server", "--port", "6379"]
    volumes:
      - ./redis-primary-data:/data
    networks:
      - redis-net

  redis-replica:
    image: redis:latest
    command: ["redis-server", "--port", "6380", "--slaveof", "redis-primary", "6379"]
    volumes:
      - ./redis-replica-data:/data
    networks:
      - redis-net

  sentinel-primary:
    image: redis:latest
    command: ["redis-server", "/etc/redis/sentinel.conf", "--sentinel"]
    depends_on:
      - redis-primary
      - redis-replica
    volumes:
      - ./sentinel-primary.conf:/etc/redis/sentinel.conf
    networks:
      - redis-net

  sentinel-replica:
    image: redis:latest
    command: ["redis-server", "/etc/redis/sentinel.conf", "--sentinel"]
    depends_on:
      - redis-primary
      - redis-replica
    volumes:
      - ./sentinel-replica.conf:/etc/redis/sentinel.conf
    networks:
      - redis-net

networks:
  redis-net:
